### ISSUE TITLE
Plugin  Cleverreach Extension Version 0.2.0 interface to contact form 7

### ISSUE THREAD

**Issue by Mario2209** [hofmannsven/cleverreach-extension#10]
Feel free to provide any kind of information you think is useful to reproduce your issue.

1. Plugin version: 0.2.0
2. WordPress version: 4.4.4.
3. Browser and operating system: Firefox
4. Your issue: Interface cleverreach extension to contact form 7

Hello,

I'm using contact form 7 and for my newsletter management I'm using cleverreach. I have installed the plugin cleverreach extension and I've tried to connect it with contact dorm 7 - but it doesn't work. I tried to add this code to functions.php

```php
add_filter( 'cleverreach_extension_container_selector', 'my_custom_cleverreach_container_selector' );
function my_custom_cleverreach_container_selector() {
  return 'wpcf7'; // General Contact Form 7 wrapper
}
```

How have I to change this code that it works?

Thanks a lot for your help.

Best regards from Germany

Mario

**Comment by hofmannsven** [comment]
Thank you very much for your feedback, Mario.

I think the best way to integrate Contact Form 7 is to upgrade to the [development version on GitHub](https://github.com/hofmannsven/cleverreach-extension). Version 0.3.0 of the plugin already extends the visual interface of the Contact Form 7 admin area so that there is no need to use the filter `cleverreach_extension_container_selector`.

Navigate to Contact Form 7: _Contact » Add Signup Form_ and setup your new signup form:

![cf7-cleverreach](https://cloud.githubusercontent.com/assets/1214387/16912641/a3cef550-4ce5-11e6-97f8-9056daef92c5.png)

You can find further information about the supported form elements in the [wiki](https://github.com/hofmannsven/cleverreach-extension/wiki/Contact-Form-7#contact-form-7).

**Comment by Mario2209** [comment]
Hello Sven, thanks a lot for your fast answer. I've updated on version 0.3.0 now. Now I have the notification on my formular that the API code is invalid and I also can't chose my formular.

I adjusted you three screenshots.

Thanks a lot for your help.

Mario

![contact form 7](https://cloud.githubusercontent.com/assets/20513670/16914396/de59ebc4-4cf1-11e6-806f-e9ef4e080c35.jpg)
![version 0 3 0](https://cloud.githubusercontent.com/assets/20513670/16914398/e1f5345a-4cf1-11e6-8992-da0a0caeec4e.jpg)
![api invalid](https://cloud.githubusercontent.com/assets/20513670/16914400/e52da954-4cf1-11e6-84cb-40a651f7e77a.jpg)

**Comment by hofmannsven** [comment]
Hi Mario, this seems like a weird caching error.
Can you please delete the last character of the API Key, save the change, and re-enter the last character? 
I think this should fix your issue. Let me know if you still have this issue otherwise.

Regards, Sven

**Comment by Mario2209** [comment]
Hi Sven,

I still have the same problem. Could it be that there is problem with the API Key?

Regards Mario

**Comment by hofmannsven** [comment]
Hi Mario, I don't see why there should be a problem with your API Key. Feel free to generate a new API Key (with read and write access rights) from your CleverReach account.

Another point of failure might be the interrelation between your _list_ and your _form_. Did you setup a form for your list with the name _Gruppe 5 (Neue Kunden)_?

![cleverreach-connect-form](https://cloud.githubusercontent.com/assets/1214387/16917206/e2e059f8-4d00-11e6-931b-99d0722b688b.png)

**Comment by Mario2209** [comment]
Dear Sven, now it works. Thanks a lot. Maybe you can help me with another problem. I have generated my contact form with contact form 7. I want that if someone chooses that he want to be informed about news etc. that automatically this contact is saved in cleverreach. Is this possible or have I do generate my contact form with cleverreach?

Thanks a lot fpr your help.

Mario

**Comment by hofmannsven** [comment]
Cool! 

You could add a checkbox to your custom signup form within Contact Form 7 like this:

```html
[checkbox checkbox id:cre_checkbox "News" "Culture" "Sport"]
```

There are even more supported form elements documented in the [wiki](https://github.com/hofmannsven/cleverreach-extension/wiki/Contact-Form-7#other-form-elements).

**Comment by Mario2209** [comment]
Hello Sven,

everything works fine now. Thanks a lot for your help. One question more. It's not about your plugin but you as a contact form 7 expert might know it. I'm tracking my contact form with google conersion tracking and I'm saving request with contact form DB. Is there a possibility to know with which keyword, google organic search or google adwords the user found the contact form?

Thanks a lot Sven. You're doing a real great job.
Kind reagards
Mario

**Comment by hofmannsven** [comment]
Thank you very much for your positive feedback. I'm glad to hear that everything works fine now. 

I'm not sure about the conversion tracking, though. Better ask an expert at the [Google Analytics Support Forums]( https://www.en.advertisercommunity.com/t5/Google-Analytics/ct-p/Google_Analytics).

Regards, Sven
