### ISSUE TITLE
Trigger JavaScipt events for success/error on signup form

### ISSUE THREAD

**Issue by stroebjo** [hofmannsven/cleverreach-extension#16]
I would suggest to add some events so your other JavaScipt can react to a successfull/error signup to the newsletter. 

Maybe something simple like a jQuery `trigger()`. For example inside `cleverreach-extension/public/js/cleverreach-extension-public.js`: 

```
success: function( response ) {
	$cr_container.find(cre.selector + cre.loading_selector).remove();
	
	if ( response.type === 'success' ) {
		$cr_container.append('<p class="' + cre.response_selector + ' ' + cre.success_selector + '">' + cre.success + '</p>');
		$cr_container.trigger('cre:success');
	} else {
		$cr_container.append('<p class="' + cre.response_selector + ' ' + cre.error_selector + '">' + response.status + '</p>');
		$cr_container.trigger('cre:error');
	}
},
```
You could than react to the form with something like: 

```
(function ($) {
	'use strict';
	$(document).ready(function () {
		$(cre.selector + cre.container_selector).on('cre:success', function() {
			// do something fancy!
		});
	});
})(jQuery);
```

I would be happy to prepare a pull request, if this would be considered.

1. Plugin version: 0.2.0
2. WordPress version: 4.7.3
3. Browser and operating system: n/a
4. Your issue: n/a

**Comment by hofmannsven** [comment]
Hi Jonathan, I really like the idea of events. I would consider this to be a huge improvement for all the people who want to hook into the plugin. Feel free to prepare a pull request!

**Comment by hofmannsven** [comment]
I've added a short documentation to the Wiki: [Custom events](https://github.com/hofmannsven/cleverreach-extension/wiki/Custom-events)
