### ISSUE TITLE
WP Plugin Repo vs. GitHub Repo Version?

### ISSUE THREAD

**Issue by stroebjo** [hofmannsven/cleverreach-extension#18]
I noticed that the WordPress Extension Repository lists the Clever Reach Extension as v0.2.0, here on the GitHub page it lists v0.3.0.

Is this intentional? What's the best way to update the extension?

Cheers,
Jonathan

**Comment by hofmannsven** [comment]
Hi, Jonathan, the GitHub repository is the development version (current beta) of the plugin.

So this is going to be the next version of the plugin as soon as all features are implemented, tested and documented. 
Nevertheless, v0.3.0 is stable and already ready for production.

For future releases, I'm going to switch to a branching model with separate branches (master/dev).

**Comment by stroebjo** [comment]
Okay, thanks for the quick answer! Do you have an estimate on a timeline when v0.3.x will be released? Maybe we could work with milestones in the GitHub Issues?

**Comment by hofmannsven** [comment]
With the official deprecation of the CleverReach SOAP API and move towards the REST API I'd like to implement an additional interface for the REST API in v0.3.x.

I currently don't have the time to handle this kind of update/extension but hope to get it done within the next couple of month.
