### ISSUE TITLE
Confirmation Message

### ISSUE THREAD

**Issue by NicheBeauty** [hofmannsven/cleverreach-extension#2]
Hello,

I've got a question. I added a custom form. If someone types his name and e-mail address and presses "Submit" no message like "Bitte bestätigen Sie.." appears. The error message "Du scheinst..." does appear, but not the success message. Within the german document "DE.po" and "DE.mo" the message is included. What do I do wrong?

Thanks for your answer!

**Comment by hofmannsven** [comment]
@NicheBeauty Did you check if the email address is blacklisted or already registered within the list? 
You can check this within your CleverReach account: _Lists » Blacklist_ (in addition each list has its own blacklist)

**Comment by NicheBeauty** [comment]
@hofmannsven I just rechecked and no my email address is not part of the blacklist and I deleted it from the group before I retry to register. The confirmation message has been sent immediately to my email account, but I don't see the message "Bitte bestätigen Sie..." below the Submit button. The error message however DOES appear. Do you have another tip for me?

**Comment by hofmannsven** [comment]
@NicheBeauty Maybe your email address is blocked because of a previous [bounce](http://support.cleverreach.de/hc/en-us/articles/202372821) or does not match the [standards](http://support.cleverreach.de/hc/en-us/articles/202372831-Why-aren-t-all-my-email-addresses-imported-) of CleverReach?

**Comment by hofmannsven** [comment]
@NicheBeauty Can you please tell me which version of the plugin you're currently working with? Did you download it via GitHub or WordPress.org? Can I check your signup form online?

If you don't feel comfortable publishing these information online, you can contact me via email: info[at]hofmannsven.com

**Comment by hofmannsven** [comment]
@NicheBeauty Thank you very much for your feedback.

As discussed response messages can be customized via filters. I've added a page with the available filters within the [Wiki](https://github.com/hofmannsven/cleverreach-extension/wiki/Custom-messages).
