### ISSUE TITLE
Bug in SOAP

### ISSUE THREAD

**Issue by rainbowinternational** [hofmannsven/cleverreach-extension#20]
Es scheint leider Probleme mit der API zu geben. Eventuell liegt das auch an unserem Serverumzug. Wobei das im selben Rechenzentrum gehostet wird. Eventuell können Sie uns weiterhelfen. Das wäre großartig. Vielen Dank!

1. Plugin version: 0.2.0
2. WordPress version: 4.9.4
3. Browser and operating system: Windows 10 Firefox 58.0.2

4. Your issue:

Fatal error: Uncaught SoapFault exception: [WSDL] SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://api.cleverreach.com/soap/interface_v5.1.php?wsdl' : failed to load external entity "http://api.cleverreach.com/soap/interface_v5.1.php?wsdl" in /home/rainbow/public_html/mfk/mfk-inhalte/plugins/cleverreach-extension/includes/api/class-cleverreach.php:25 Stack trace: #0 /home/rainbow/public_html/mfk/mfk-inhalte/plugins/cleverreach-extension/includes/api/class-cleverreach.php(25): SoapClient->SoapClient('http://api.clev...') #1 /home/rainbow/public_html/mfk/mfk-inhalte/plugins/cleverreach-extension/admin/class-cre-admin.php(372): CleverreachExtension\Core\Api\Cleverreach->__construct() #2 [internal function]: CleverreachExtension\Viewadmin\Cre_Admin->render_api_key_field(Array) #3 /home/rainbow/public_html/mfk/wp-admin/includes/template.php(1378): call_user_func(Array, Array) #4 /home/rainbow/public_html/mfk/wp-admin/includes/template.php(1337): do_settings_fields('cleverreach-ext...', 'cleverreach_ext...') #5 /home/rainb in /home/rainbow/public_html/mfk/mfk-inhalte/plugins/cleverreach-extension/includes/api/class-cleverreach.php on line 25

**Comment by hofmannsven** [comment]
Vielen Dank für das Feedback.
Auf den ersten Blick sieht es tatsächlich nach einem Problem mit Server und SoapClient aus.

Im Wiki habe ich einen Eintrag zum Setup der [PHP SOAP Extension](https://github.com/hofmannsven/cleverreach-extension/wiki/PHP-SOAP-Extension) erstellt.

Des Weiteren ist auf GitHub eine neue Version des Plugins (beta) verfügbar, bei der der Aufruf der SOAP Extension optimiert wurde:
» https://github.com/hofmannsven/cleverreach-extension/archive/master.zip
