### ISSUE TITLE
Other values for "form_id" do not work

### ISSUE THREAD

**Issue by stippi** [hofmannsven/cleverreach-extension#22]
Hi,

I've installed version 0.2.0 of the plugin. From the screenshot, where the shortcode is given the form-id parameter, it looked as if one could embed different forms on different pages. However, it only seems to work when a list and form is selected in the plugin preferences, of which the form id is integrated into the "generated" shortcode, and then if this shortcode is placed with the same form_id, then subscription actually works. If a different form_id (a valid one of course) is provided, it only appears to work, but subscription does not happen and no Opt-In mail is sent.

My question is: Why not use the plugin settings as a way to generate a shortcode that will work, but allow different form_ids to be passed to the shortcode where forms are actually embedded?

WordPress version: 4.8.2

Thanks a lot & best regards,
-Stephan

**Comment by hofmannsven** [comment]
This works as of version 0.3.0
