### ISSUE TITLE
Error "undefined" after submit

### ISSUE THREAD

**Issue by Dreamfish19** [hofmannsven/cleverreach-extension#5]
1. Plugin version: 0.2.0
2. WordPress version: 4.5.1
3. Browser and operating system: Chrome, Win 10
4. Your issue: The plugin was working without any problems. After the last two wordpress updates, it responded after hitting submit with "undefined". I had to save the settings in the wordpress backend again to regain normal functionality. 

What could cause this error?

**Comment by hofmannsven** [comment]
Thank you very much for reporting this. 
I upgraded my site in my development environment various times from different WordPress versions but I could not reproduce the error.
WordPress 4.5 ships with jQuery 1.12.3 so maybe there was a problem with another plugins script on the site? Saving the settings normally clears the cache and maybe this solved the error?
I will monitor this issue for any future updates but I don't know what causes this error on your site.

**Comment by Dreamfish19** [comment]
Hi,

thanks for your answer. This weekend the same error occured again, but this time without any other update on the site. Is there any "debug" mode in your plugin I could enable to trace this error?

**Comment by Dreamfish19** [comment]
Hi Sven,

the error happens now every day :( 
Is there anything I can do to debug this error?

Cheers,
Alex

**Comment by hofmannsven** [comment]
Sorry, there is no debug mode yet.
Maybe you can try the upcoming version (see [master branch](https://github.com/hofmannsven/cleverreach-extension/tree/master)) of the plugin:
» https://github.com/hofmannsven/cleverreach-extension/archive/master.zip

**Comment by Dreamfish19** [comment]
Hi, I'm currently testing with the upcoming version 0.3.0. At first it did not work. I had to flush the cache from my hoster (raidboxes). They are using nginx. Could this be a problem?

**Comment by Dreamfish19** [comment]
Hi, sorry for my late response!
After contacting raidboxes, I disabled NGINX caching, and the problem disappeard immediately.
It really had something todo witch caching ..

**Comment by hofmannsven** [comment]
Okay and thank you very much for your feedback!
