### ISSUE TITLE
Api call flooding on page hits

### ISSUE THREAD

**Issue by senuphtyz** [hofmannsven/cleverreach-extension#6]
Hello

1. Plugin version: master (6cc94ef1b7b875a5cc1fbdfb5bd00b076f3d821e)
2. WordPress version: 4.5
3. Browser and operating system: (curl / chrome)
4. Your issue:

We used the shortcode to append the form in our footer.
`[cleverreach_extension form_id="custom" list_id="XXXXXX" source=""]`

Tcpdump tells me that our server is constantly doing API calls for every page load.
(Cleverreach stats tells us about 30k per day .. site is not live yet).

Maybe i just forgot a configuration option to set or something like this.

Best regards,
Bruno

**Comment by hofmannsven** [comment]
Thank you for your feedback.
I've patched the plugin to catch the API calls internally.

The cached transients will be alive for 12 hours. Making changes in the plugin settings will clear the cache.
