### ISSUE TITLE
Contact Form 7 elements

### ISSUE THREAD

**Issue by konsumkuenstler** [hofmannsven/cleverreach-extension#8]
Hey Sven,

ich nutze deine Erweiterung in Kombination mit CF7. Das läuft soweit auch ganz unproblematisch. Allerdings unterstütz deine Erweiterung leider keine checkboxen - diese werden bei Cleverreach als "Array" eingetragen statt den tatsächlichen Values.

Kannst du mir erklären woran das liegt? Ich komme selbst nach dem durchforsten deiner Plugin-Struktur nicht darauf.

**Comment by hofmannsven** [comment]
Vielen Dank für das Feedback.
Die Checkboxen wurden tatsächlich nicht richtig verarbeitet. Ich habe das Plugin entsprechend angepasst.

Der Code für die Checkbox in Contact Form 7 sieht bei mir so aus:
```
[checkbox checkbox id:cre_checkbox "Option 1" "Option 2"]
```

**Comment by hofmannsven** [comment]
Ich habe auch das [Wiki](https://github.com/hofmannsven/cleverreach-extension/wiki/Contact-Form-7) bzgl. der unterstützen Elemente aktualisiert.

**Comment by konsumkuenstler** [comment]
Perfekt! Danke dir vielmals für deine Unterstützung!
